### ISSUE TITLE
Attempting to copy resource from HS to JH results in tuple error

### ISSUE THREAD

**Issue by kylecombes** [kylecombes/hydroshare-jupyter-gui#4]
Steps to reproduce:
1. Open resource list page in web app
2. Click on a resource that exists in HS but not in JH
3. HS files are shown in the web app, but JH files are not shown

The following error is output to the server console:
```
[E 200209 14:25:02 web:1788] Uncaught exception GET /resources/655a7ab5283f495b9104c0abdce80fa8/local-files (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/resources/655a7ab5283f495b9104c0abdce80fa8/local-files', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/kyle/developer/cuahsi/.venv/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/kyle/developer/cuahsi/hydroshare-jupyterhub-gui/backend/hydroshare_gui/hs_server.py", line 77, in get
        jh_files = resource.get_files_JH()
      File "/home/kyle/developer/cuahsi/hydroshare-jupyterhub-gui/backend/hydroshare_gui/resource.py", line 45, in get_files_JH
        self.save_resource_locally()
      File "/home/kyle/developer/cuahsi/hydroshare-jupyterhub-gui/backend/hydroshare_gui/resource.py", line 36, in save_resource_locally
        self.hs.getResource(self.res_id, destination=self.output_folder, unzip=unzip)
      File "/home/kyle/developer/cuahsi/.venv/lib/python3.6/site-packages/hs_restclient/__init__.py", line 590, in getResource
        stream = self._getBagStream(pid, wait_for_bag_creation)
      File "/home/kyle/developer/cuahsi/.venv/lib/python3.6/site-packages/hs_restclient/__init__.py", line 637, in _getBagStream
        raise HydroShareHTTPException((bag_url, 'GET', r.status_code))
      File "/home/kyle/developer/cuahsi/.venv/lib/python3.6/site-packages/hs_restclient/exceptions.py", line 66, in __init__
        self.status_msg = args[3]
    IndexError: tuple index out of range
[E 200209 14:25:02 web:2246] 500 GET /resources/655a7ab5283f495b9104c0abdce80fa8/local-files (127.0.0.1) 18069.09ms```

**Comment by vickymmcd** [comment]
Has this been resolved? I haven't seen this as an issue..

**Comment by kylecombes** [comment]
Yeah, resolved.
